var runner = TestRunner()

await PermissionTests.run(&runner)
await ASRProviderTests.run(&runner)
await CloudASRTests.run(&runner)
await RecognitionSessionTests.run(&runner)
await OOBELayoutTests.run(&runner)
await CapsuleAnimationTests.run(&runner)
await AppSettingsNotificationTests.run(&runner)
await AppSettingsBackendTests.run(&runner)
await RecordingStateMachineTests.run(&runner)
await RecordingSessionControllerTests.run(&runner)
await RecordingLatencyTests.run(&runner)
await RecordingSessionPresenterTests.run(&runner)
await KeychainTests.run(&runner)
await AudioRouterTests.run(&runner)
await AudioEngineConcurrencyTests.run(&runner)
await RecognitionFinalizerTests.run(&runner)
await PunctuationTests.run(&runner)
await PasteCompatibilityProfileTests.run(&runner)
await PasteboardServiceTests.run(&runner)
await TextInjectionLifecycleTests.run(&runner)
await UpdateCheckerTests.run(&runner)
await LLMRefinerTests.run(&runner)
await LLMAPIKeyMigrationTests.run(&runner)
await HeadphoneHIDTests.run(&runner)
await SherpaPreloadTests.run(&runner)
await SingleInstanceControllerTests.run(&runner)
await SherpaDownloadCapsulePresenterTests.run(&runner)
await SherpaLifecycleCoordinatorTests.run(&runner)
await RecordingStateBroadcasterTests.run(&runner)
#if DEBUG_BUILD
await DebugAudioEvidenceRecorderTests.run(&runner)
#endif

runner.finish()
